"""Read every result JSON and (re)generate paper/results_macros.tex with all
numeric macros. Missing results fall back to a visible [TBD]. Run after any stage
completes; then rebuild the PDF.
"""
import os, json
R = "results"; OUT = "paper/results_macros.tex"

def j(p):
    p = os.path.join(R, p)
    return json.load(open(p)) if os.path.exists(p) else None

def tex(x, fmt="{}"):
    return fmt.format(x) if x is not None else r"\textbf{[TBD]}"

m = {}
# constants already known
m["naoUranyl"] = "221"; m["tgradDF"] = "3.3"; m["tgradNoDF"] = "50"

# --- relativistic effect ---
d = j("dft/relativistic_effect.json")
if d:
    m["ruoX"] = f"{d['x2c']['r_min']:.3f}"
    m["ruoNR"] = f"{d['nonrel']['r_min']:.3f}"
    m["dcontraction"] = f"{abs(d['contraction_A'])*100:.1f}"
# basis-consistent (decontracted) recompute (Reviewer-1 response)
dd = j("dft/rel_effect_decontracted.json")
if dd:
    m["dconPM"] = f"{dd['decontracted']['contraction_pm']:.1f}"
    m["dconConPM"] = f"{dd['contracted']['contraction_pm']:.1f}"
# T1 diagnostic
t1 = j("dft/t1_diagnostic.json")
if t1:
    m["Tone"] = f"{t1['t1_diagnostic']:.3f}"

# --- scCO2 density (worst & best error) ---
d = j("scco2/density_validation.json")
if d:
    errs = [(x["P_bar"], x["pct_err"]) for x in d]
    m["scErr"] = (f"+{min(abs(e) for _,e in errs):.0f}\\% at 30~MPa to "
                  f"+{max(e for _,e in errs):.0f}\\% near $P_c$")

# --- scCO2 solvation FE (CH4 @ 150 bar) ---
d = j("scco2/solvation_fe.json")
if d:
    ch4 = [x for x in d if x["solute"] == "CH4-UA" and abs(x["P_bar"]-150) < 1]
    if ch4:
        x = ch4[0]
        m["dGch"] = f"\\SI{{{x['dG_solv_kJ']:.1f} \\pm {x['dG_err_kJ']:.1f}}}{{kJ/mol}}"
        m["minoverlap"] = f"{x['min_overlap_adjacent']:.2f}"

# --- MLP ---
meta = j("mlp/dataset_meta.json")
if meta:
    m["mlpNframes"] = str(meta.get("n_frames", ""))
    tf = meta.get("top_freqs_cm", [])
    if tf:
        m["uostretch"] = f"{max(tf):.0f}~cm$^{{-1}}$"
ev = j("mlp/mlp_eval.json")
if ev:
    m["mlpEtest"] = f"{ev['rmse']['test']['energy']*1000:.2f}"
    m["mlpFtest"] = f"{ev['rmse']['test']['force']*1000:.0f}"
    m["mlpEood"] = f"{ev['rmse']['ood']['energy']*1000:.2f}"
    m["mlpFood"] = f"{ev['rmse']['ood']['force']*1000:.0f}"
    fbe = ev.get("f_rmse_by_element", {}).get("test", {})
    if "U" in fbe and "H" in fbe:
        m["mlpEleak"] = f"U {fbe['U']*1000:.0f} vs H {fbe['H']*1000:.0f}~meV/\\AA"

# --- generative ---
g = j("generative/generative_results.json")
if g:
    if "surrogate" in g:
        m["surrR"] = f"{g['surrogate'].get('r2_scaffold', float('nan')):.2f}"
    me = g.get("metrics_extractant", {})
    m["genNovelty"] = f"{me.get('novelty',0)*100:.0f}\\%"
    m["genUniq"] = f"{me.get('uniqueness',0)*100:.0f}\\%"
rs = j("generative/rescore_results.json")
if rs:
    import numpy as _np
    dd = [x.get("ddE_AcLa_kJ") for x in rs if x.get("ddE_AcLa_kJ") is not None
          and _np.isfinite(x.get("ddE_AcLa_kJ"))]
    if dd:
        m["ddEsel"] = f"\\SI{{{_np.mean(dd):.0f} \\pm {_np.std(dd):.0f}}}{{kJ/mol}}"
sa = j("generative/synth_audit.json")
if sa:
    m["saMed"] = f"{sa['sa_median']:.1f}"; m["saMin"] = f"{sa['sa_min']:.1f}"; m["saMax"] = f"{sa['sa_max']:.1f}"

ALL = ["ruoX","ruoNR","dcontraction","naoUranyl","tgradDF","tgradNoDF","mlpNframes",
       "mlpEtest","mlpFtest","mlpEood","mlpFood","mlpEleak","uostretch","scErr",
       "dGch","minoverlap","surrR","genNovelty","genUniq","ddEsel",
       "dconPM","dconConPM","Tone","saMed","saMin","saMax"]
with open(OUT, "w") as f:
    f.write("% auto-generated by fill_macros.py -- do not edit by hand\n")
    for k in ALL:
        v = m.get(k, r"\textbf{[TBD]}")
        f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
print("wrote", OUT)
for k in ALL:
    print(f"  \\{k} = {m.get(k, 'TBD')}")
